"""added price and admission date for ward beds

Revision ID: 10afbcca9d49
Revises: a8fb101393b1
Create Date: 2025-10-03 22:49:07.610613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10afbcca9d49'
down_revision = 'a8fb101393b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ward_beds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admission_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ward_beds', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('admission_date')

    # ### end Alembic commands ###
