"""updated the tables

Revision ID: 13c2d489638d
Revises: 3a8064a45cdb
Create Date: 2025-10-20 00:12:25.344253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13c2d489638d'
down_revision = '3a8064a45cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescriptions_medicines', sa.Column('taken_by', sa.String(length=50), nullable=True))
    op.add_column('prescriptions_medicines', sa.Column('taken_by_phone_no', sa.String(length=50), nullable=True))
    op.alter_column('prescriptions_medicines', 'prescription_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('prescriptions_surgeries', 'prescription_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('prescriptions_tests', 'prescription_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prescriptions_tests', 'prescription_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('prescriptions_surgeries', 'prescription_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('prescriptions_medicines', 'prescription_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('prescriptions_medicines', 'taken_by_phone_no')
    op.drop_column('prescriptions_medicines', 'taken_by')
    # ### end Alembic commands ###
