"""added price to surgeries table

Revision ID: 14688edaf99d
Revises: 6060d8c51da9
Create Date: 2025-10-04 12:18:26.101317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14688edaf99d'
down_revision = '6060d8c51da9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surgeries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surgeries', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
