"""added billing surgeries and billing beds

Revision ID: 26645045b3a2
Revises: 10afbcca9d49
Create Date: 2025-10-03 23:15:51.899468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26645045b3a2'
down_revision = '10afbcca9d49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_beds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False))
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_beds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
