"""added status column for the user type and user field table

Revision ID: 44e842aa43fb
Revises: e3d4550d19ab
Create Date: 2025-10-01 12:06:21.830992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e842aa43fb'
down_revision = 'e3d4550d19ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_field', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='userfieldstatustypeenum'), nullable=False))

    with op.batch_alter_table('user_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='usertypestatusenum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_type', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('user_field', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
