"""updated the surgery table and test table of purchase

Revision ID: 4c30d21912d8
Revises: e75bec3cfc36
Create Date: 2025-10-20 02:45:44.818114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c30d21912d8'
down_revision = 'e75bec3cfc36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order', 'order_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order', sa.Column('order_date', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
