"""removed requested by for lab reports tables

Revision ID: 57fdbf6d43d8
Revises: c25e3f28b4b9
Create Date: 2025-09-29 01:41:18.966658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57fdbf6d43d8'
down_revision = 'c25e3f28b4b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_report', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('lab_report_reported_by_fkey'), type_='foreignkey')
        batch_op.drop_column('reported_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reported_by', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('lab_report_reported_by_fkey'), 'user', ['reported_by'], ['id'])

    # ### end Alembic commands ###
