"""added is billed to orders table

Revision ID: 5fcf3d1a682b
Revises: f3c195b13c66
Create Date: 2025-10-20 01:08:12.806331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fcf3d1a682b'
down_revision = 'f3c195b13c66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_billed', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('prescriptions_patient_id_fkey'), 'prescriptions', type_='foreignkey')
    op.drop_column('prescriptions', 'is_billed')
    op.drop_column('prescriptions', 'patient_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescriptions', sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('prescriptions', sa.Column('is_billed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('prescriptions_patient_id_fkey'), 'prescriptions', 'user', ['patient_id'], ['id'])
    op.drop_column('orders', 'is_billed')
    # ### end Alembic commands ###
