"""added is billed and other is_deleted to prescritions table

Revision ID: 6060d8c51da9
Revises: f9003031f01b
Create Date: 2025-10-04 11:48:56.611758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6060d8c51da9'
down_revision = 'f9003031f01b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_billed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('is_billed')

    # ### end Alembic commands ###
