"""updated the surgery table and test table of purchase

Revision ID: 73293ffdcd3f
Revises: 7d01aae13955
Create Date: 2025-10-20 01:52:28.957358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73293ffdcd3f'
down_revision = '7d01aae13955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_test', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_test', 'status')
    # ### end Alembic commands ###
