"""removed log one in the billing and added payments table

Revision ID: 7678039f8c72
Revises: 86ef4619bebc
Create Date: 2025-10-03 18:21:53.971129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7678039f8c72'
down_revision = '86ef4619bebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billing_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('transaction_ref', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['billing_id'], ['billing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('billing', schema=None) as batch_op:
        batch_op.drop_column('logs')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logs', sa.TEXT(), autoincrement=False, nullable=True))

    op.drop_table('payments')
    # ### end Alembic commands ###
