"""create tables

Revision ID: 7a1875b7503c
Revises: b70805384fe8
Create Date: 2025-09-29 22:39:22.065973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a1875b7503c'
down_revision = 'b70805384fe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('prescriptions_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['patient_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('prescriptions_user_id_fkey'), 'user', ['user_id'], ['id'])
        batch_op.drop_column('patient_id')

    # ### end Alembic commands ###
