"""updated the purchase surgery table

Revision ID: 7d01aae13955
Revises: 5fcf3d1a682b
Create Date: 2025-10-20 01:41:05.607434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d01aae13955'
down_revision = '5fcf3d1a682b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescriptions_tests', sa.Column('status', sa.String(), nullable=True))
    op.add_column('purchase_surgery', sa.Column('surgery_type_id', sa.Integer(), nullable=False))
    op.add_column('purchase_surgery', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('purchase_surgery', sa.Column('scheduled_date', sa.DateTime(), nullable=True))
    op.add_column('purchase_surgery', sa.Column('status', sa.String(length=30), nullable=True))
    op.add_column('purchase_surgery', sa.Column('notes', sa.Text(), nullable=True))
    op.drop_constraint(op.f('purchase_surgery_surgery_id_fkey'), 'purchase_surgery', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_surgery', 'surgery_types', ['surgery_type_id'], ['id'])
    op.drop_column('purchase_surgery', 'surgery_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_surgery', sa.Column('surgery_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'purchase_surgery', type_='foreignkey')
    op.create_foreign_key(op.f('purchase_surgery_surgery_id_fkey'), 'purchase_surgery', 'surgeries', ['surgery_id'], ['id'])
    op.drop_column('purchase_surgery', 'notes')
    op.drop_column('purchase_surgery', 'status')
    op.drop_column('purchase_surgery', 'scheduled_date')
    op.drop_column('purchase_surgery', 'price')
    op.drop_column('purchase_surgery', 'surgery_type_id')
    op.drop_column('prescriptions_tests', 'status')
    # ### end Alembic commands ###
