"""added surgery doctors table

Revision ID: 86ef4619bebc
Revises: a8824b3fc083
Create Date: 2025-10-03 17:21:32.449236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ef4619bebc'
down_revision = 'a8824b3fc083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surgery_doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surgery_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['surgery_id'], ['surgeries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surgery_doctors')
    # ### end Alembic commands ###
