"""removed mandatory start time for surgeries table

Revision ID: 8c27fe0c2286
Revises: 14688edaf99d
Create Date: 2025-10-04 12:40:34.911610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c27fe0c2286'
down_revision = '14688edaf99d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surgeries', schema=None) as batch_op:
        batch_op.alter_column('scheduled_start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surgeries', schema=None) as batch_op:
        batch_op.alter_column('scheduled_start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###
