"""added billing table

Revision ID: 8c9cb40894c3
Revises: 1fd215925eda
Create Date: 2025-09-30 00:13:14.701231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c9cb40894c3'
down_revision = '1fd215925eda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_medicines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))

    with op.batch_alter_table('billing_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_tests', schema=None) as batch_op:
        batch_op.drop_column('price')

    with op.batch_alter_table('billing_medicines', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
