"""create tables

Revision ID: 903f31acf6e0
Revises: 7a1875b7503c
Create Date: 2025-09-29 22:46:05.997564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903f31acf6e0'
down_revision = '7a1875b7503c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('prescriptions_tests_medicine_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'lab_test', ['test_id'], ['id'])
        batch_op.drop_column('medicine_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medicine_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('prescriptions_tests_medicine_id_fkey'), 'medicine', ['medicine_id'], ['id'])
        batch_op.drop_column('test_id')

    # ### end Alembic commands ###
