"""added billing table

Revision ID: 9a74064c8242
Revises: 8c9cb40894c3
Create Date: 2025-09-30 00:14:00.491984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a74064c8242'
down_revision = '8c9cb40894c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing', schema=None) as batch_op:
        batch_op.alter_column('prescription_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing', schema=None) as batch_op:
        batch_op.alter_column('prescription_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
