"""added prescription id to orders table

Revision ID: a0b5f951d4d7
Revises: 13c2d489638d
Create Date: 2025-10-20 00:37:32.013628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0b5f951d4d7'
down_revision = '13c2d489638d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('prescription_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'prescriptions', ['prescription_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'prescription_id')
    # ### end Alembic commands ###
