"""updated the purchase surgery table

Revision ID: a7566e450c84
Revises: 4c30d21912d8
Create Date: 2025-10-20 03:58:00.025895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7566e450c84'
down_revision = '4c30d21912d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing', sa.Column('order_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('billing_prescription_id_key'), 'billing', type_='unique')
    op.drop_constraint(op.f('billing_prescription_id_fkey'), 'billing', type_='foreignkey')
    op.drop_constraint(op.f('billing_patient_id_fkey'), 'billing', type_='foreignkey')
    op.create_foreign_key(None, 'billing', 'orders', ['order_id'], ['id'])
    op.drop_column('billing', 'patient_id')
    op.drop_column('billing', 'prescription_id')
    op.add_column('orders', sa.Column('total_amount', sa.Float(), nullable=True))
    op.drop_column('orders', 'is_billed')
    op.drop_constraint(op.f('prescriptions_surgeries_surgery_id_fkey'), 'prescriptions_surgeries', type_='foreignkey')
    op.drop_column('prescriptions_surgeries', 'surgery_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescriptions_surgeries', sa.Column('surgery_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('prescriptions_surgeries_surgery_id_fkey'), 'prescriptions_surgeries', 'surgeries', ['surgery_id'], ['id'])
    op.add_column('orders', sa.Column('is_billed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('orders', 'total_amount')
    op.add_column('billing', sa.Column('prescription_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('billing', sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'billing', type_='foreignkey')
    op.create_foreign_key(op.f('billing_patient_id_fkey'), 'billing', 'user', ['patient_id'], ['id'])
    op.create_foreign_key(op.f('billing_prescription_id_fkey'), 'billing', 'prescriptions', ['prescription_id'], ['id'])
    op.create_unique_constraint(op.f('billing_prescription_id_key'), 'billing', ['prescription_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('billing', 'order_id')
    # ### end Alembic commands ###
