"""added surgery table

Revision ID: a8824b3fc083
Revises: c5e5ee511f19
Create Date: 2025-10-03 17:20:09.707315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8824b3fc083'
down_revision = 'c5e5ee511f19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surgeries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('surgery_type_id', sa.Integer(), nullable=False),
    sa.Column('operation_theatre_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_start_time', sa.DateTime(), nullable=False),
    sa.Column('scheduled_end_time', sa.DateTime(), nullable=True),
    sa.Column('actual_start_time', sa.DateTime(), nullable=True),
    sa.Column('actual_end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['operation_theatre_id'], ['operation_theatres.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['surgery_type_id'], ['surgery_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surgeries')
    # ### end Alembic commands ###
