"""removed doctor id from the billing table

Revision ID: a8fb101393b1
Revises: 7678039f8c72
Create Date: 2025-10-03 21:35:53.356168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8fb101393b1'
down_revision = '7678039f8c72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('billing_doctor_id_fkey'), type_='foreignkey')
        batch_op.drop_column('doctor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('billing_doctor_id_fkey'), 'user', ['doctor_id'], ['id'])

    # ### end Alembic commands ###
