"""removed requested by for lab request tables

Revision ID: c25e3f28b4b9
Revises: 41a95bc3a4b3
Create Date: 2025-09-29 01:37:27.596600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c25e3f28b4b9'
down_revision = '41a95bc3a4b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_request', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('lab_request_requested_by_fkey'), type_='foreignkey')
        batch_op.drop_column('requested_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_by', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('lab_request_requested_by_fkey'), 'user', ['requested_by'], ['id'])

    # ### end Alembic commands ###
