"""added dynamic database url

Revision ID: c9ecf8ccc38e
Revises: 1bdcb37cda2d
Create Date: 2025-10-11 18:57:34.129086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9ecf8ccc38e'
down_revision = '1bdcb37cda2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subdomain', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('db_uri', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['subdomain'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_info', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('db_uri')
        batch_op.drop_column('subdomain')

    # ### end Alembic commands ###
