"""updated the surgery table and test table of purchase

Revision ID: d0556d78a40a
Revises: 73293ffdcd3f
Create Date: 2025-10-20 01:58:59.236765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0556d78a40a'
down_revision = '73293ffdcd3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_surgery', sa.Column('scheduled_start_time', sa.DateTime(), nullable=True))
    op.add_column('purchase_surgery', sa.Column('scheduled_end_time', sa.DateTime(), nullable=True))
    op.add_column('purchase_surgery', sa.Column('actual_start_time', sa.DateTime(), nullable=True))
    op.add_column('purchase_surgery', sa.Column('actual_end_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_surgery', 'actual_end_time')
    op.drop_column('purchase_surgery', 'actual_start_time')
    op.drop_column('purchase_surgery', 'scheduled_end_time')
    op.drop_column('purchase_surgery', 'scheduled_start_time')
    # ### end Alembic commands ###
