"""delete created by column from the wards table

Revision ID: e3d4550d19ab
Revises: 01a88246593a
Create Date: 2025-10-01 12:02:07.441734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3d4550d19ab'
down_revision = '01a88246593a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ward', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ward_created_by_fkey'), type_='foreignkey')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ward', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('ward_created_by_fkey'), 'user', ['created_by'], ['id'])

    # ### end Alembic commands ###
