"""updated the surgery table and test table of purchase

Revision ID: e75bec3cfc36
Revises: d0556d78a40a
Create Date: 2025-10-20 02:01:59.870973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e75bec3cfc36'
down_revision = 'd0556d78a40a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_surgery', sa.Column('operation_theatre_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchase_surgery', 'operation_theatres', ['operation_theatre_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_surgery', type_='foreignkey')
    op.drop_column('purchase_surgery', 'operation_theatre_id')
    # ### end Alembic commands ###
