"""Add status column with default to billing

Revision ID: e99844638511
Revises: 1d997cb648f6
Create Date: 2025-09-30 00:41:13.702724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e99844638511'
down_revision = '1d997cb648f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), server_default='PENDING', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
