"""added is active and is deleted to user type table 

Revision ID: ea8d80b7f55c
Revises: c7b445f76a1f
Create Date: 2025-10-04 17:52:18.699017

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea8d80b7f55c'
down_revision = 'c7b445f76a1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))

    with op.batch_alter_table('user_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', name='usertypestatusenum'), autoincrement=False, nullable=False))
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
