"""added is active and is deleted to medicine table

Revision ID: ed25e5e80c98
Revises: d10931311540
Create Date: 2025-10-04 19:32:43.066742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed25e5e80c98'
down_revision = 'd10931311540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
